//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.15 at 04:34:49 PM WAT 
//

package org.openmrs.module.openhmis.ndrmodel;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ConsumptionSummaryType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConsumptionSummaryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DepartmentCode" type="{}DepartmentType"/>
 *         &lt;element name="ItemCode" type="{}ItemCodeType"/>
 *         &lt;element name="TotalQuantityReceived" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="TotalQuantityConsumed" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="StockBalance" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConsumptionSummaryType", propOrder = {
        "departmentCode",
        "itemCode",
        "totalQuantityReceived",
        "totalQuantityConsumed",
        "stockBalance"
})
public class ConsumptionSummaryType {

	@XmlElement(name = "DepartmentCode")
	@XmlSchemaType(name = "positiveInteger")
	protected int departmentCode;
	@XmlElement(name = "ItemCode")
	@XmlSchemaType(name = "positiveInteger")
	protected int itemCode;
	@XmlElement(name = "TotalQuantityReceived", required = true)
	protected BigInteger totalQuantityReceived;
	@XmlElement(name = "TotalQuantityConsumed", required = true)
	protected BigInteger totalQuantityConsumed;
	@XmlElement(name = "StockBalance", required = true)
	protected BigInteger stockBalance;

	/**
	 * Gets the value of the departmentCode property.
	 */
	public int getDepartmentCode() {
		return departmentCode;
	}

	/**
	 * Sets the value of the departmentCode property.
	 */
	public void setDepartmentCode(int value) {
		this.departmentCode = value;
	}

	/**
	 * Gets the value of the itemCode property.
	 */
	public int getItemCode() {
		return itemCode;
	}

	/**
	 * Sets the value of the itemCode property.
	 */
	public void setItemCode(int value) {
		this.itemCode = value;
	}

	/**
	 * Gets the value of the totalQuantityReceived property.
	 * @return possible object is {@link BigInteger }
	 */
	public BigInteger getTotalQuantityReceived() {
		return totalQuantityReceived;
	}

	/**
	 * Sets the value of the totalQuantityReceived property.
	 * @param value allowed object is {@link BigInteger }
	 */
	public void setTotalQuantityReceived(BigInteger value) {
		this.totalQuantityReceived = value;
	}

	/**
	 * Gets the value of the totalQuantityConsumed property.
	 * @return possible object is {@link BigInteger }
	 */
	public BigInteger getTotalQuantityConsumed() {
		return totalQuantityConsumed;
	}

	/**
	 * Sets the value of the totalQuantityConsumed property.
	 * @param value allowed object is {@link BigInteger }
	 */
	public void setTotalQuantityConsumed(BigInteger value) {
		this.totalQuantityConsumed = value;
	}

	/**
	 * Gets the value of the stockBalance property.
	 * @return possible object is {@link BigInteger }
	 */
	public BigInteger getStockBalance() {
		return stockBalance;
	}

	/**
	 * Sets the value of the stockBalance property.
	 * @param value allowed object is {@link BigInteger }
	 */
	public void setStockBalance(BigInteger value) {
		this.stockBalance = value;
	}

}
