//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.08 at 09:37:53 PM WAT 
//

package org.openmrs.module.openhmis.ndrmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ConsumptionSummaryType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConsumptionSummaryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DepartmentCode" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="ItemCode" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="TotalQuantityReceived" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="TotalQuantityConsumed" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="StockBalance" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConsumptionSummaryType", propOrder = {
        "departmentCode",
        "itemCode",
        "totalQuantityReceived",
        "totalQuantityConsumed",
        "stockBalance"
})
public class ConsumptionSummaryType {

	@XmlElement(name = "DepartmentCode")
	protected byte departmentCode;
	@XmlElement(name = "ItemCode")
	protected byte itemCode;
	@XmlElement(name = "TotalQuantityReceived")
	protected byte totalQuantityReceived;
	@XmlElement(name = "TotalQuantityConsumed")
	protected byte totalQuantityConsumed;
	@XmlElement(name = "StockBalance")
	protected byte stockBalance;

	/**
	 * Gets the value of the departmentCode property.
	 */
	public byte getDepartmentCode() {
		return departmentCode;
	}

	/**
	 * Sets the value of the departmentCode property.
	 */
	public void setDepartmentCode(byte value) {
		this.departmentCode = value;
	}

	/**
	 * Gets the value of the itemCode property.
	 */
	public byte getItemCode() {
		return itemCode;
	}

	/**
	 * Sets the value of the itemCode property.
	 */
	public void setItemCode(byte value) {
		this.itemCode = value;
	}

	/**
	 * Gets the value of the totalQuantityReceived property.
	 */
	public byte getTotalQuantityReceived() {
		return totalQuantityReceived;
	}

	/**
	 * Sets the value of the totalQuantityReceived property.
	 */
	public void setTotalQuantityReceived(byte value) {
		this.totalQuantityReceived = value;
	}

	/**
	 * Gets the value of the totalQuantityConsumed property.
	 */
	public byte getTotalQuantityConsumed() {
		return totalQuantityConsumed;
	}

	/**
	 * Sets the value of the totalQuantityConsumed property.
	 */
	public void setTotalQuantityConsumed(byte value) {
		this.totalQuantityConsumed = value;
	}

	/**
	 * Gets the value of the stockBalance property.
	 */
	public byte getStockBalance() {
		return stockBalance;
	}

	/**
	 * Sets the value of the stockBalance property.
	 */
	public void setStockBalance(byte value) {
		this.stockBalance = value;
	}

}
