//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.22 at 10:03:06 PM WAT 
//

package org.openmrs.module.openhmis.ndrmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MessageHeader" type="{}MessageHeaderType"/>
 *         &lt;choice>
 *           &lt;element name="InventoryReport" type="{}InventoryReportType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "messageHeader",
        "inventoryReport"
})
@XmlRootElement(name = "Container")
public class Container {

	@XmlElement(name = "MessageHeader", required = true)
	protected MessageHeaderType messageHeader;
	@XmlElement(name = "InventoryReport")
	protected InventoryReportType inventoryReport;

	/**
	 * Gets the value of the messageHeader property.
	 * @return possible object is {@link MessageHeaderType }
	 */
	public MessageHeaderType getMessageHeader() {
		return messageHeader;
	}

	/**
	 * Sets the value of the messageHeader property.
	 * @param value allowed object is {@link MessageHeaderType }
	 */
	public void setMessageHeader(MessageHeaderType value) {
		this.messageHeader = value;
	}

	/**
	 * Gets the value of the inventoryReport property.
	 * @return possible object is {@link InventoryReportType }
	 */
	public InventoryReportType getInventoryReport() {
		return inventoryReport;
	}

	/**
	 * Sets the value of the inventoryReport property.
	 * @param value allowed object is {@link InventoryReportType }
	 */
	public void setInventoryReport(InventoryReportType value) {
		this.inventoryReport = value;
	}

}
