//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.25 at 12:43:37 PM WAT 
//

package org.openmrs.module.openhmis.ndrmodel;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for DrugType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DrugType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ItemName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="QuantityPrescribed" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="QuantityDispensed" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="Duration" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="DrugStrength" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DrugCategory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DrugType", propOrder = {
        "itemName",
        "quantityPrescribed",
        "quantityDispensed",
        "duration",
        "drugStrength",
        "drugCategory"
})
public class DrugType {

	@XmlElement(name = "ItemName", required = true)
	protected String itemName;
	@XmlElement(name = "QuantityPrescribed", required = true)
	protected BigInteger quantityPrescribed;
	@XmlElement(name = "QuantityDispensed", required = true)
	protected BigInteger quantityDispensed;
	@XmlElement(name = "Duration", required = true)
	protected BigInteger duration;
	@XmlElement(name = "DrugStrength", required = true)
	protected String drugStrength;
	@XmlElement(name = "DrugCategory", required = true)
	protected String drugCategory;

	/**
	 * Gets the value of the itemName property.
	 * @return possible object is {@link String }
	 */
	public String getItemName() {
		return itemName;
	}

	/**
	 * Sets the value of the itemName property.
	 * @param value allowed object is {@link String }
	 */
	public void setItemName(String value) {
		this.itemName = value;
	}

	/**
	 * Gets the value of the quantityPrescribed property.
	 * @return possible object is {@link BigInteger }
	 */
	public BigInteger getQuantityPrescribed() {
		return quantityPrescribed;
	}

	/**
	 * Sets the value of the quantityPrescribed property.
	 * @param value allowed object is {@link BigInteger }
	 */
	public void setQuantityPrescribed(BigInteger value) {
		this.quantityPrescribed = value;
	}

	/**
	 * Gets the value of the quantityDispensed property.
	 * @return possible object is {@link BigInteger }
	 */
	public BigInteger getQuantityDispensed() {
		return quantityDispensed;
	}

	/**
	 * Sets the value of the quantityDispensed property.
	 * @param value allowed object is {@link BigInteger }
	 */
	public void setQuantityDispensed(BigInteger value) {
		this.quantityDispensed = value;
	}

	/**
	 * Gets the value of the duration property.
	 * @return possible object is {@link BigInteger }
	 */
	public BigInteger getDuration() {
		return duration;
	}

	/**
	 * Sets the value of the duration property.
	 * @param value allowed object is {@link BigInteger }
	 */
	public void setDuration(BigInteger value) {
		this.duration = value;
	}

	/**
	 * Gets the value of the drugStrength property.
	 * @return possible object is {@link String }
	 */
	public String getDrugStrength() {
		return drugStrength;
	}

	/**
	 * Sets the value of the drugStrength property.
	 * @param value allowed object is {@link String }
	 */
	public void setDrugStrength(String value) {
		this.drugStrength = value;
	}

	/**
	 * Gets the value of the drugCategory property.
	 * @return possible object is {@link String }
	 */
	public String getDrugCategory() {
		return drugCategory;
	}

	/**
	 * Sets the value of the drugCategory property.
	 * @param value allowed object is {@link String }
	 */
	public void setDrugCategory(String value) {
		this.drugCategory = value;
	}

}
