//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.30 at 03:49:03 PM WAT 
//

package org.openmrs.module.openhmis.ndrmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ItemType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ItemType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ItemCode" type="{}ItemCodeType"/>
 *         &lt;element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="ExpirationDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Batch" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ItemType", propOrder = {
        "itemCode",
        "quantity",
        "expirationDate",
        "batch"
})
public class ItemType {

	@XmlElement(name = "ItemCode")
	@XmlSchemaType(name = "positiveInteger")
	protected int itemCode;
	@XmlElement(name = "Quantity")
	protected short quantity;
	@XmlElement(name = "ExpirationDate", required = true)
	protected String expirationDate;
	@XmlElement(name = "Batch", required = true)
	protected String batch;

	/**
	 * Gets the value of the itemCode property.
	 */
	public int getItemCode() {
		return itemCode;
	}

	/**
	 * Sets the value of the itemCode property.
	 */
	public void setItemCode(int value) {
		this.itemCode = value;
	}

	/**
	 * Gets the value of the quantity property.
	 */
	public short getQuantity() {
		return quantity;
	}

	/**
	 * Sets the value of the quantity property.
	 */
	public void setQuantity(short value) {
		this.quantity = value;
	}

	/**
	 * Gets the value of the expirationDate property.
	 * @return possible object is {@link String }
	 */
	public String getExpirationDate() {
		return expirationDate;
	}

	/**
	 * Sets the value of the expirationDate property.
	 * @param value allowed object is {@link String }
	 */
	public void setExpirationDate(String value) {
		this.expirationDate = value;
	}

	/**
	 * Gets the value of the batch property.
	 * @return possible object is {@link String }
	 */
	public String getBatch() {
		return batch;
	}

	/**
	 * Sets the value of the batch property.
	 * @param value allowed object is {@link String }
	 */
	public void setBatch(String value) {
		this.batch = value;
	}

}
