//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.08 at 09:37:53 PM WAT 
//

package org.openmrs.module.openhmis.ndrmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for NewConsumptionType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NewConsumptionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ConsumptionDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TestingPointCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ItemCode" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="ItemBatch" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TotalUsed" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TotalWastage-Loses" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TestPurposeCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NewConsumptionType", propOrder = {
        "consumptionDate",
        "testingPointCode",
        "itemCode",
        "itemBatch",
        "totalUsed",
        "totalWastageLoses",
        "testPurposeCode"
})
public class NewConsumptionType {

	@XmlElement(name = "ConsumptionDate", required = true)
	protected String consumptionDate;
	@XmlElement(name = "TestingPointCode", required = true)
	protected String testingPointCode;
	@XmlElement(name = "ItemCode")
	protected byte itemCode;
	@XmlElement(name = "ItemBatch", required = true)
	protected String itemBatch;
	@XmlElement(name = "TotalUsed", required = true)
	protected String totalUsed;
	@XmlElement(name = "TotalWastage-Loses", required = true)
	protected String totalWastageLoses;
	@XmlElement(name = "TestPurposeCode", required = true)
	protected String testPurposeCode;

	/**
	 * Gets the value of the consumptionDate property.
	 * @return possible object is {@link String }
	 */
	public String getConsumptionDate() {
		return consumptionDate;
	}

	/**
	 * Sets the value of the consumptionDate property.
	 * @param value allowed object is {@link String }
	 */
	public void setConsumptionDate(String value) {
		this.consumptionDate = value;
	}

	/**
	 * Gets the value of the testingPointCode property.
	 * @return possible object is {@link String }
	 */
	public String getTestingPointCode() {
		return testingPointCode;
	}

	/**
	 * Sets the value of the testingPointCode property.
	 * @param value allowed object is {@link String }
	 */
	public void setTestingPointCode(String value) {
		this.testingPointCode = value;
	}

	/**
	 * Gets the value of the itemCode property.
	 */
	public byte getItemCode() {
		return itemCode;
	}

	/**
	 * Sets the value of the itemCode property.
	 */
	public void setItemCode(byte value) {
		this.itemCode = value;
	}

	/**
	 * Gets the value of the itemBatch property.
	 * @return possible object is {@link String }
	 */
	public String getItemBatch() {
		return itemBatch;
	}

	/**
	 * Sets the value of the itemBatch property.
	 * @param value allowed object is {@link String }
	 */
	public void setItemBatch(String value) {
		this.itemBatch = value;
	}

	/**
	 * Gets the value of the totalUsed property.
	 * @return possible object is {@link String }
	 */
	public String getTotalUsed() {
		return totalUsed;
	}

	/**
	 * Sets the value of the totalUsed property.
	 * @param value allowed object is {@link String }
	 */
	public void setTotalUsed(String value) {
		this.totalUsed = value;
	}

	/**
	 * Gets the value of the totalWastageLoses property.
	 * @return possible object is {@link String }
	 */
	public String getTotalWastageLoses() {
		return totalWastageLoses;
	}

	/**
	 * Sets the value of the totalWastageLoses property.
	 * @param value allowed object is {@link String }
	 */
	public void setTotalWastageLoses(String value) {
		this.totalWastageLoses = value;
	}

	/**
	 * Gets the value of the testPurposeCode property.
	 * @return possible object is {@link String }
	 */
	public String getTestPurposeCode() {
		return testPurposeCode;
	}

	/**
	 * Sets the value of the testPurposeCode property.
	 * @param value allowed object is {@link String }
	 */
	public void setTestPurposeCode(String value) {
		this.testPurposeCode = value;
	}

}
