//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.22 at 10:03:06 PM WAT 
//

package org.openmrs.module.openhmis.ndrmodel;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the
 * org.openmrs.module.openhmis.ndrmodel package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content. The
 * Java representation of XML content can consist of schema derived interfaces and classes representing the binding of schema
 * type definitions, element declarations and model groups. Factory methods for each of these are provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

	/**
	 * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
	 * org.openmrs.module.openhmis.ndrmodel
	 */
	public ObjectFactory() {}

	/**
	 * Create an instance of {@link Container }
	 */
	public Container createContainer() {
		return new Container();
	}

	/**
	 * Create an instance of {@link MessageHeaderType }
	 */
	public MessageHeaderType createMessageHeaderType() {
		return new MessageHeaderType();
	}

	/**
	 * Create an instance of {@link InventoryReportType }
	 */
	public InventoryReportType createInventoryReportType() {
		return new InventoryReportType();
	}

	/**
	 * Create an instance of {@link ConsumptionReportType }
	 */
	public ConsumptionReportType createConsumptionReportType() {
		return new ConsumptionReportType();
	}

	/**
	 * Create an instance of {@link ReceiptOperationType }
	 */
	public ReceiptOperationType createReceiptOperationType() {
		return new ReceiptOperationType();
	}

	/**
	 * Create an instance of {@link DisposedType }
	 */
	public DisposedType createDisposedType() {
		return new DisposedType();
	}

	/**
	 * Create an instance of {@link DisposedOperationType }
	 */
	public DisposedOperationType createDisposedOperationType() {
		return new DisposedOperationType();
	}

	/**
	 * Create an instance of {@link ItemType }
	 */
	public ItemType createItemType() {
		return new ItemType();
	}

	/**
	 * Create an instance of {@link TransferOperationType }
	 */
	public TransferOperationType createTransferOperationType() {
		return new TransferOperationType();
	}

	/**
	 * Create an instance of {@link ReturnType }
	 */
	public ReturnType createReturnType() {
		return new ReturnType();
	}

	/**
	 * Create an instance of {@link TransferType }
	 */
	public TransferType createTransferType() {
		return new TransferType();
	}

	/**
	 * Create an instance of {@link DistributionOperationType }
	 */
	public DistributionOperationType createDistributionOperationType() {
		return new DistributionOperationType();
	}

	/**
	 * Create an instance of {@link AdjustmentType }
	 */
	public AdjustmentType createAdjustmentType() {
		return new AdjustmentType();
	}

	/**
	 * Create an instance of {@link ReturnOperationType }
	 */
	public ReturnOperationType createReturnOperationType() {
		return new ReturnOperationType();
	}

	/**
	 * Create an instance of {@link ReceiptType }
	 */
	public ReceiptType createReceiptType() {
		return new ReceiptType();
	}

	/**
	 * Create an instance of {@link AdjustmentOperationType }
	 */
	public AdjustmentOperationType createAdjustmentOperationType() {
		return new AdjustmentOperationType();
	}

	/**
	 * Create an instance of {@link ConsumptionSummaryType }
	 */
	public ConsumptionSummaryType createConsumptionSummaryType() {
		return new ConsumptionSummaryType();
	}

	/**
	 * Create an instance of {@link OperationItemType }
	 */
	public OperationItemType createOperationItemType() {
		return new OperationItemType();
	}

	/**
	 * Create an instance of {@link MessageSendingOrganisationType }
	 */
	public MessageSendingOrganisationType createMessageSendingOrganisationType() {
		return new MessageSendingOrganisationType();
	}

	/**
	 * Create an instance of {@link TaskOperationType }
	 */
	public TaskOperationType createTaskOperationType() {
		return new TaskOperationType();
	}

	/**
	 * Create an instance of {@link NewConsumptionType }
	 */
	public NewConsumptionType createNewConsumptionType() {
		return new NewConsumptionType();
	}

	/**
	 * Create an instance of {@link DistributionType }
	 */
	public DistributionType createDistributionType() {
		return new DistributionType();
	}

}
