//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.25 at 12:43:37 PM WAT 
//

package org.openmrs.module.openhmis.ndrmodel;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for PharmacyConsumptionSummaryType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PharmacyConsumptionSummaryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Drug" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TotalQuantityReceived" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="DrugCategory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DispensingModel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PharmacyConsumptionSummaryType", propOrder = {
        "drug",
        "totalQuantityReceived",
        "drugCategory",
        "dispensingModel"
})
public class PharmacyConsumptionSummaryType {

	@XmlElement(name = "Drug", required = true)
	protected String drug;
	@XmlElement(name = "TotalQuantityReceived", required = true)
	protected BigInteger totalQuantityReceived;
	@XmlElement(name = "DrugCategory", required = true)
	protected String drugCategory;
	@XmlElement(name = "DispensingModel", required = true)
	protected String dispensingModel;

	/**
	 * Gets the value of the drug property.
	 * @return possible object is {@link String }
	 */
	public String getDrug() {
		return drug;
	}

	/**
	 * Sets the value of the drug property.
	 * @param value allowed object is {@link String }
	 */
	public void setDrug(String value) {
		this.drug = value;
	}

	/**
	 * Gets the value of the totalQuantityReceived property.
	 * @return possible object is {@link BigInteger }
	 */
	public BigInteger getTotalQuantityReceived() {
		return totalQuantityReceived;
	}

	/**
	 * Sets the value of the totalQuantityReceived property.
	 * @param value allowed object is {@link BigInteger }
	 */
	public void setTotalQuantityReceived(BigInteger value) {
		this.totalQuantityReceived = value;
	}

	/**
	 * Gets the value of the drugCategory property.
	 * @return possible object is {@link String }
	 */
	public String getDrugCategory() {
		return drugCategory;
	}

	/**
	 * Sets the value of the drugCategory property.
	 * @param value allowed object is {@link String }
	 */
	public void setDrugCategory(String value) {
		this.drugCategory = value;
	}

	/**
	 * Gets the value of the dispensingModel property.
	 * @return possible object is {@link String }
	 */
	public String getDispensingModel() {
		return dispensingModel;
	}

	/**
	 * Sets the value of the dispensingModel property.
	 * @param value allowed object is {@link String }
	 */
	public void setDispensingModel(String value) {
		this.dispensingModel = value;
	}

}
