//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.25 at 12:43:37 PM WAT 
//

package org.openmrs.module.openhmis.ndrmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for PharmacyNewConsumptionType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PharmacyNewConsumptionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ConsumptionDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ConsumptionUUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PatientID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TreatmentType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="VisitType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PickUpReason" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DispensingModel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Drugs" type="{}DrugItemType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PharmacyNewConsumptionType", propOrder = {
        "consumptionDate",
        "consumptionUUID",
        "patientID",
        "treatmentType",
        "visitType",
        "pickUpReason",
        "dispensingModel",
        "drugs"
})
public class PharmacyNewConsumptionType {

	@XmlElement(name = "ConsumptionDate", required = true)
	protected String consumptionDate;
	@XmlElement(name = "ConsumptionUUID", required = true)
	protected String consumptionUUID;
	@XmlElement(name = "PatientID", required = true)
	protected String patientID;
	@XmlElement(name = "TreatmentType", required = true)
	protected String treatmentType;
	@XmlElement(name = "VisitType", required = true)
	protected String visitType;
	@XmlElement(name = "PickUpReason", required = true)
	protected String pickUpReason;
	@XmlElement(name = "DispensingModel", required = true)
	protected String dispensingModel;
	@XmlElement(name = "Drugs", required = true)
	protected DrugItemType drugs;

	/**
	 * Gets the value of the consumptionDate property.
	 * @return possible object is {@link String }
	 */
	public String getConsumptionDate() {
		return consumptionDate;
	}

	/**
	 * Sets the value of the consumptionDate property.
	 * @param value allowed object is {@link String }
	 */
	public void setConsumptionDate(String value) {
		this.consumptionDate = value;
	}

	/**
	 * Gets the value of the consumptionUUID property.
	 * @return possible object is {@link String }
	 */
	public String getConsumptionUUID() {
		return consumptionUUID;
	}

	/**
	 * Sets the value of the consumptionUUID property.
	 * @param value allowed object is {@link String }
	 */
	public void setConsumptionUUID(String value) {
		this.consumptionUUID = value;
	}

	/**
	 * Gets the value of the patientID property.
	 * @return possible object is {@link String }
	 */
	public String getPatientID() {
		return patientID;
	}

	/**
	 * Sets the value of the patientID property.
	 * @param value allowed object is {@link String }
	 */
	public void setPatientID(String value) {
		this.patientID = value;
	}

	/**
	 * Gets the value of the treatmentType property.
	 * @return possible object is {@link String }
	 */
	public String getTreatmentType() {
		return treatmentType;
	}

	/**
	 * Sets the value of the treatmentType property.
	 * @param value allowed object is {@link String }
	 */
	public void setTreatmentType(String value) {
		this.treatmentType = value;
	}

	/**
	 * Gets the value of the visitType property.
	 * @return possible object is {@link String }
	 */
	public String getVisitType() {
		return visitType;
	}

	/**
	 * Sets the value of the visitType property.
	 * @param value allowed object is {@link String }
	 */
	public void setVisitType(String value) {
		this.visitType = value;
	}

	/**
	 * Gets the value of the pickUpReason property.
	 * @return possible object is {@link String }
	 */
	public String getPickUpReason() {
		return pickUpReason;
	}

	/**
	 * Sets the value of the pickUpReason property.
	 * @param value allowed object is {@link String }
	 */
	public void setPickUpReason(String value) {
		this.pickUpReason = value;
	}

	/**
	 * Gets the value of the dispensingModel property.
	 * @return possible object is {@link String }
	 */
	public String getDispensingModel() {
		return dispensingModel;
	}

	/**
	 * Sets the value of the dispensingModel property.
	 * @param value allowed object is {@link String }
	 */
	public void setDispensingModel(String value) {
		this.dispensingModel = value;
	}

	/**
	 * Gets the value of the drugs property.
	 * @return possible object is {@link DrugItemType }
	 */
	public DrugItemType getDrugs() {
		return drugs;
	}

	/**
	 * Sets the value of the drugs property.
	 * @param value allowed object is {@link DrugItemType }
	 */
	public void setDrugs(DrugItemType value) {
		this.drugs = value;
	}

}
